name: CI tests

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '8.8.3'
            cabal: '3.0'
          - ghc: '8.10.7'
            cabal: '3.0'
          - ghc: '9.0.1'
            cabal: '3.4'
    steps:
    - uses: actions/checkout@v1
    - name: Install recent cabal/ghc
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.versions.ghc }}
        cabal-version: ${{ matrix.versions.cabal }}

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --disable-optimization -fexecutable all
    - name: Build and test
      run: |
          cabal v2-build --enable-tests --disable-optimization -fexecutable all

  macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: |
          curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz -o stack.tar.gz
          tar xzvf stack.tar.gz --strip-components=1 'stack*/stack'
    - name: Install dependencies
      run: |
          ./stack update
          ./stack test --dependencies-only --fast
    - name: Build and test
      run: |
          ./stack install --fast --test --haddock --no-haddock-deps

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      shell: cmd
      run: |
          choco install haskell-stack
    - name: Install dependencies
      run: |
          stack update
          stack test --dependencies-only --fast
    - name: Build and test
      shell: cmd
      run: |
          chcp 65001
          stack install --test --fast
